### ISSUE TITLE
Can't Run After Build

### ISSUE THREAD

**Issue by TomAshley303** [ludios/node-blake2#3]
This is driving me crazy...

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/Code/project/node_modules/blake2/index.js:9:17)
```

This happens no matter how many times I remove node_modules and run every npm update/install/whatever commands there are.

**Comment by ivan** [comment]
Could there be a mismatch between the version of node that your `npm` uses and the version of node that Electron uses?  I can't think of any other reason why that would happen, if you're clearing out `node_modules`.

If that's not the case, please let me know how to set up the environment you have, so that I can reproduce this.

**Comment by TomAshley303** [comment]
npm: 3.10.6
node (system): 6.4.0
package.json...

`{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/electron/electron-quick-start/issues"
  },
  "homepage": "https://github.com/electron/electron-quick-start#readme",
  "devDependencies": {
    "electron-prebuilt": "^1.3.4"
  },
  "dependencies": {
    "blake2": "github:ludios/node-blake2",
    "chokidar": "^1.6.0"
  }
}`

**Comment by TomAshley303** [comment]
It was working before I upgraded the project's packages. So when I got  the error I updated npm, node, my globals.

**Comment by ivan** [comment]
I believe this is the relevant issue:

https://github.com/electron-userland/electron-prebuilt/issues/172

https://github.com/electron/electron/issues/5851

You can probably fix this by downgrading electron-prebuilt until they fix their release.

**Comment by ivan** [comment]
https://github.com/mccollam/comrade/commit/5c85cc4cacdc93f9ff48fcf8846b5bd23067a53f went back to electron-prebuilt 1.2.8; that should probably work.

**Comment by ivan** [comment]
Alternatively, the electron issue suggests that you can pass extra arguments to `npm` to get ABI compatibility with Electron, but I can't test that to see if it works.

**Comment by TomAshley303** [comment]
Thanks. Can't I just run prebuilt and pass the project directory to it or something? /looks to see if there's a CLI help

**Comment by TomAshley303** [comment]
Eh, sorry. I realize this is a problem people have with any arbitrary package but I tried the version of prebuilt you suggested and the same thing still happened. meh.

**Comment by TomAshley303** [comment]
Same error.. even when I run electron manually.

**Comment by ivan** [comment]
Did you specify it with `"1.2.8"` (no `^`) and clear out `node_modules`?

**Comment by TomAshley303** [comment]
electron-prebuilt is deprecated. just switched to "electron" and all is fine with that.
