### ISSUE TITLE
TypeError: If key argument is given, it must be a Buffer

### ISSUE THREAD

**Issue by TomAshley303** [ludios/node-blake2#4]
My code was fine until I updated but now I'm getting:

```
Uncaught Exception:
TypeError: If key argument is given, it must be a Buffer
    at TypeError (native)
    at new Hash
```

The code is:

```
    const hash = new blake2.Hash('blake2b');
    hash.setEncoding('hex');
    const HashStream = fs.createReadStream(`${path}`);
    HashStream.on('end', function(){
      hash.end();
      const digest = hash.read();
    });
    HashStream.pipe(hash);
```

**Comment by ivan** [comment]
I'm not sure why you're seeing this, since it doesn't look like you're using `KeyedHash`.  `Hash` [passes null](https://github.com/ludios/node-blake2/blob/master/index.js#L52) for `key`, and it's [compared here](https://github.com/ludios/node-blake2/blob/master/src/binding.cpp#L61) which should result in that code block being skipped.  Moreover, the node-blake2 tests pass and [b2sum.js](https://github.com/ludios/node-blake2/blob/master/b2sum.js) seems to work here.

Are you sure that code is the code you're running?  Does b2sum work for you?  Of course, it is possible that there is something very strange going on.  If there is a bug here, can you send a full test case that I can run?

**Comment by ivan** [comment]
Are you running this in Electron?  Does this work outside Electron, with just `node`?

I wonder if Electron subtly broke the ABI in a way that would cause `IsNull` checks or some of the other C++ code to misbehave.

**Comment by TomAshley303** [comment]
Just emailed you main.js

**Comment by TomAshley303** [comment]
lol back to the module version mismatch crap. I give up on life.

**Comment by ivan** [comment]
Have you tried rebuilding for ABI version 48, like the instructions here?

https://github.com/octalmage/robotjs/wiki/Electron

(change `target` to the latest Electron version, though.)

**Comment by ivan** [comment]
I haven't tested this, but the general solution seems to be

1) use electron-prebuilt 1.1.3

or 2) make npm build C++ addons for the newer ABI that Electron uses (49 instead of 48?)

or 3) avoid C++ addons like node-blake2

Please reopen if this bug still manifests.

**Comment by TomAshley303** [comment]
I tried running the command to rebuild which didn't work and then adding "rebuild": "npm rebuild --runtime=electron --target=1.1.3 --disturl=https://atom.io/download/atom-shell --abi=48"  to my packages.json and reinstalling everything but still got...

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/blake2/index.js:9:17)

package.json looks like:

{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "rebuild": "npm rebuild --runtime=electron --target=1.1.3 --disturl=https://atom.io/download/atom-shell -$
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/electron/electron-quick-start/issues"
  },
  "homepage": "https://github.com/electron/electron-quick-start#readme",
  "devDependencies": {
    "electron": "1.3.4"
  },
  "dependencies": {
    "blake2": "github:ludios/node-blake2",
    "chokidar": "^1.2.8"
  }
}

**Comment by TomAshley303** [comment]
I've tried using previous versions of electron (Not desirable but whatever) and get the same result. I guess I'll try some other versions again. Not using blake2 isn't an option.

**Comment by ivan** [comment]
Try `--target=1.3.4`; it's supposed to match the electron version.

**Comment by ivan** [comment]
And do run `npm rebuild` after doing that; not sure what `npm install` would do, but it probably builds with the wrong ABI.

**Comment by ivan** [comment]
If that doesn't work, please ask someone who knows how `electron-rebuild` works, because I haven't used it.

**Comment by TomAshley303** [comment]
okay.. npm install doesn't fix it. Neither does npm rebuild by itself even with the abi specified in package.json BUT after adding that line to package.json, installing, and then rebuilding with _npm rebuild --runtime=electron --target=1.1.3 --disturl=https://atom.io/download/atom-shell --abi=49_ it works! I should say though that 49 isn't even referenced here: [https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/abi_crosswalk.json](https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/abi_crosswalk.json) but it works.

Thanks for helping to troubleshoot it. I should probably make some rounds on stack exchange because all answers say "Reinstall your packages" and mention nothing of rebuild (Unless I just didn't happen upon the answer somewhere).
