### ISSUE TITLE
Failing to start module because of NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by Belleal** [ludios/node-blake2#8]
Hi there, I am using this module locally without problems. However, when I am deploying our application to GCloud using Docker containers with automated build, the application fails to start with the following error:

> message:  "The module '/usr/src/titanium/node_modules/blake2/build/Release/binding.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 57. This version of Node.js requires
> NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`)."     
>     stack:  "Error: The module '/usr/src/titanium/node_modules/blake2/build/Release/binding.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 57. This version of Node.js requires
> NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/usr/src/titanium/node_modules/blake2/index.js:9:17)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)"     

I've tried cleaning the npm cache, running npm rebuild, and various combinations but to no avail. This is the part of the Docker file I am using for the deployment:

> ...
> COPY package*.json ./
> #RUN npm cache clean --force
> RUN npm install -g npm@latest
> RUN npm install --only=production
> #RUN npm rebuild
> RUN npm audit fix
> ...

The problems happens with both Node versions 10.15.1 and 11.10.0 but only in the cloud environment. As I mentioned above, I have no issues running the same thing locally with either Node versions.

**Comment by ivan** [comment]
I don't work with Docker, so I don't have a solution, but I think you would encounter this error with any node C++ addon. There might be a relevant solution somewhere if you search around for 'NODE_MODULE_VERSION Docker'.

**Comment by Belleal** [comment]
Alright, I'll try. First time I encounter this error with a module, but maybe I haven't used other C++ modules so far.

**Comment by Belleal** [comment]
Ok, I finally managed to solve this. The issue indeed was related to a mismatched version between compilation time of blake2 and Docker runtime. In case anyone else encounters this problem when deploying to GCloud and Kubernetes, this is what you need to watch for:
1. Make sure to specify the exact node.js version you plan to use in the container in the _cloudbuild.yaml_ as well:
```
steps:
  - name: 'node:10.15.2'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:10.15.2'
    entrypoint: 'npm'
    args: ['audit', 'fix']
  - name: 'node:10.15.2'
    entrypoint: 'npm'
    args: ['test']
...
```
2. Specify the same version of node.js in the beginning of the _Dockerfile_:
```
FROM node:10.15.2
...
```
This will ensure that all the npm modules are compiled against the same runtime version as the one you plan to run the services on.

**Comment by likunlovecode** [comment]
I tried to introduce blake2, but I couldn't find the corresponding module.
This relative module was not found:

* ./build/Release/binding in ./node_modules/blake2/index.js
